config/routes.rb
Rails.application.routes.draw do

  get '/yc_fellowship', to: 'pages#dashboard'
  get '/dashboard', to: 'pages#dashboard'
  get '/catalogue', to: 'pages#catalogue'

  resources :invites, only: [:new, :index, :create, :destroy] do
    collection do
      get 'activation/:invite_code', to: 'invites#activation', as: :activation
      get 'share', to: 'invites#share_invite_url_frontoffice'
      post 'create_account'
      post 'wizard_invite_done'
      post 'request_demo'
    end
  end
  resources :companies, only: [:update] do
    collection do
      get 'configure'
    end
  end
  resources :carts, only: [:create, :destroy, :update]
  resources :item_subscriptions, path: 'subscriptions', only: [:index, :edit, :update, :destroy, :create] do
    collection do
      get 'create_subscriptions'
      get 'pre_checkout'
    end
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pages/index'
  get 'pages/dashboard'
  get 'pages/catalogue'

  devise_for :users, path: 'account',
  path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' },
  controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  resources :items
  resources :item_categories

  resource :users do
    get 'new_credit_card', as: :new_credit_card
    post 'save_credit_card'
  end

  root 'pages#landing'

end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController

  EMAILS_TO_NOTIFY = ['stefano@workful.co', 'elena@workful.co']

  layout "frontoffice", only: [:new, :share_invite_url_frontoffice]
  skip_before_filter :authenticate_user!, only: [:activation, :create_account, :request_demo]

  def index
  end

  def share_invite_url_frontoffice
    @company = current_user.company
  end

  def request_demo
    req = Request.new(
      fullname: params['name'],
      email: params['email'],
      company_name: params['company']
    )
    if req.save
      EMAILS_TO_NOTIFY.each do |mail|
        ApplicationMailer.notify_demo_request(mail, req).deliver_later
      end
      # as now we will send this email
      #ApplicationMailer.request_demo_confirmation(req.email).deliver_later
      render json: {result: 'OK'}
    else
      render json: {result: 'SEND_ERROR'}
    end
  end

  def activation
    @company = Company.find_by_invite_code(params[:invite_code])
    redirect_to root_url unless @company.present? || current_user
    @user = User.new
    @user.company = @company
  end

  def create_account
    if params[:user][:password] == "" or params[:user][:password].length < 6
      redirect_to activation_invites_path(params[:invite_code]), flash[:error] => "The password is short"
    else
      @company = Company.where(invite_code: params[:invite_code]).take
      if @company.present?
        @user = User.new(params_user)
        @user.monthly_budget = @company.monthly_budget
        @user.email = @user.email + '@' + @company.domain
        if @user.save
          CompanyUser.create(company_id: @company.id, user_id: @user.id, role_in_company: 'user')
          sign_in @user
          redirect_to authenticated_url
        else
          redirect_to activation_invites_path(params[:invite_code]), flash[:error] => "Something is wrong"
        end 
      else
        redirect_to root_url, flash[:error] => "Something is wrong"
      end
    end
  end

  def wizard_invite_done
    redirect_to authenticated_url, notice: ""
  end

  private
  def params_user
    params[:user].permit(:first_name, :last_name, :email, :password)
  end

  def redirect_if_logged_in
    redirect_to authenticated_url if current_user
  end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/activation.html.erb
<div class="signup-page">
  <div class="container">
    <div class="box">
      <h2 class="text-center">Join to <%= @company.name %></h2>

      <%= form_for(@user, url: create_account_invites_path) do |f| %>
        <div class="row">
          <div class="col-md-6">
            <div class="field">
              <%= f.label :first_name %><br />
              <%= f.text_field :first_name, autofocus: true, class: 'form-control' %>
            </div>
          </div>
          <div class="col-md-6">
            <div class="field">
              <%= f.label :last_name %><br />
              <%= f.text_field :last_name, autofocus: true, class: 'form-control' %>
            </div>
          </div>
        </div>

        <br />
        <div class="field">
          <%= label_tag 'Company Name' %><br />
          <%= @company.name %>
        </div>
        <br />

        <%= hidden_field_tag :company_id, @company.id %>
        <%= hidden_field_tag :invite_code, @company.invite_code %>

        <div class="field">
          <%= f.label :email %><br />
          <div class="form-inline">
          <%= f.text_field :email, autofocus: true, class: 'form-control' %> <span>@ <%= @company.domain %></span>
          </div>
        </div>

        <div class="field">
          <%= f.label :password %>
          <em>(8 characters minimum)</em>
          <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
        </div>
        <br />
        <div class="actions">
          <%= f.submit "Sign up", class: "btn-success btn-full-width btn" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/invites/index.html.erb
<h1>Invites#index</h1>
<p>Find me in app/views/invites/index.html.erb</p>

app/views/invites/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 box-white">
      <h1>Invites</h1>
      <div class="users-invited">
        <% if @invites.count > 0 %>
          <% @invites.each do |invite| %>
            <div class="col-md-3">
              <%= invite.first_name %>
            </div>

            <div class="col-md-3">
              <%= invite.last_name %>
            </div>

            <div class="col-md-3">
              <%= invite.email %>
            </div>

            <div class="col-md-3">
              <div class="col-md-6">
                $ <%= invite.monthly_budget %>
              </div>

              <div class="col-md-6">
                Actions
              </div>
            </div>
          <% end %>
        <% else %>
          <p class="text-center no-users">No invites yet, start adding one!</p>
        <% end %>
      </div>
      <h4>Add a new user</h4>
      <div class="user-invite row">
        <%= form_for @invite, remote: true, validate: true do |f| %> 
          <div class="col-md-3 field">
            <%= f.text_field :first_name, placeholder: 'First Name', class: 'form-control' %>
          </div>
          <div class="col-md-3 field">
            <%= f.text_field :last_name, placeholder: 'Last Name', class: 'form-control' %>
          </div>
          <div class="col-md-3 field">
            <%= f.text_field :email, placeholder: 'Email', class: 'form-control' %>
          </div>
          <div class="col-md-3 field">
            <div class="col-md-6 field" style="padding-right: 0px;">
              <div class="row">
                <div class="col-md-3" style="padding: 10px; padding-left: 23px; font-size: 18px; margin-left: -27px;">
                  $
                </div>
                <div class="col-md-9" style="padding-right: 0px;">
                  <%= f.text_field :monthly_budget, placeholder: '100', class: 'form-control' %>
                </div>
              </div>
            </div>
            <div class="col-md-3" style="padding-left: 0px;">
              <%= f.submit 'Send Invite', class: 'btn btn-lg btn-warning' %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="row actions">
        <div class="col-md-12" style="text-align: center; padding-top: 30px;">
          <%= link_to "Ok, I've done", wizard_invite_done_invites_path, class: "btn btn-lg btn-success", method: :post %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/invites/share_invite_url_frontoffice.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 box-white">
      <h1>Share this url with all your employees</h1>
      <div class="alert alert-warning" role="alert">
        <a href="mailto:?subject=Join workful?body=asdadasd"><%= activation_invites_url(@company.invite_code) %></a>
      </div>
      <div class="row actions">
        <div class="col-md-12" style="text-align: center; padding-top: 30px;">
          <%= link_to "Ok, I've done", authenticated_path, class: "btn btn-lg btn-success" %>
        </div>
      </div>
    </div>
  </div>
</div>