config/routes.rb
Rails.application.routes.draw do

  get '/yc_fellowship', to: 'pages#dashboard'
  get '/dashboard', to: 'pages#dashboard'
  get '/catalogue', to: 'pages#catalogue'

  resources :invites, only: [:new, :index, :create, :destroy] do
    collection do
      get 'activation/:invite_code', to: 'invites#activation', as: :activation
      get 'share', to: 'invites#share_invite_url_frontoffice'
      post 'create_account'
      post 'wizard_invite_done'
      post 'request_demo'
    end
  end
  resources :companies, only: [:update] do
    collection do
      get 'configure'
    end
  end
  resources :carts, only: [:create, :destroy, :update]
  resources :item_subscriptions, path: 'subscriptions', only: [:index, :edit, :update, :destroy, :create] do
    collection do
      get 'create_subscriptions'
      get 'pre_checkout'
    end
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pages/index'
  get 'pages/dashboard'
  get 'pages/catalogue'

  devise_for :users, path: 'account',
  path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' },
  controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  resources :items
  resources :item_categories

  resource :users do
    get 'new_credit_card', as: :new_credit_card
    post 'save_credit_card'
  end

  root 'pages#landing'

end

app/views/shared/_cart_create.html.erb
<div id="shopping-cart">
  <%= render 'shared/shopping_cart', total_checkout: @total_checkout %>
</div>

app/views/shared/_cart_element.html.erb
<li class="order-item" style="padding-top: 30px;">
  <table class="table-bordered">
    <tbody>
      <tr>
        <td style="width: 150px; position: relative;">
          <div>
            <%= form_tag cart_path(cart_element.id), method: :delete, remote: true do %>
              <%= hidden_field_tag :cart_id, cart_element.id %>
              <%= submit_tag "x", style: "position:absolute; top: 0px; right: 0px; padding: 2px;" %>
            <% end %>
          </div>
          <div>
            <p style="text-align: center;"><%= cart_element.item.description %></p>
            <div style="padding: 0 35px; height: 80px;"><%= image_tag cart_element.item.image, width: '80px'%></div>
          </div>
        </td>
        <td style="width: 120px; text-align: center;">
          <div>
            <%= form_tag cart_path(cart_element.id), method: :patch, remote: true, id: cart_element.id do %>
              <%= hidden_field_tag :cart_id, cart_element.id %>
              <%= select_tag :amount, options_for_select([["25$", 25], ["50$", 50], ["75$", 75], ["100$", 100], ["125$", 125], ["150$", 150], ["175$", 175], ["200$", 200]], selected: cart_element.amount.to_i), onchange: ("$('##{cart_element.id}').submit()") %>
          <% end %>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
</li>

app/views/shared/_catalogue_modal.html.erb
<div class="modal add-perk-modal" id="perk-<%= perk.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <h3 class="modal-title" id="myModalLabel" style="text-align:center;">Add <strong><%= perk.name %></strong> to your perks</h3>
        <p class="lead text-center">Set your monthly budget:</p>
        <div class="row">
          <div class="col-lg-4 col-md-4 col-sm-4"></div>
          <div class="col-lg-4 col-md-4 col-sm-4" style="margin-top:20px; margin-bottom:20px;">
            <%= form_tag item_subscriptions_path, remote: true, method: :post, id: perk.id do %>
              <div class="form-group pull-left">
                <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
                <%= hidden_field_tag 'item_subscription[item_id]', perk.id %>
                <%= select_tag 'item_subscription[amount]', options_for_select([["25$", 25], ["50$", 50], ["75$", 75], ["100$", 100], ["125$", 125], ["150$", 150], ["175$", 175], ["200$", 200]], selected: 100), class: 'form-control' %>
              </div>
              <%= submit_tag 'Confirm', class: 'btn btn-success pull-right add-perk-submit', name: nil, 'aria-label' => 'Close' %>
            <% end %>
          </div>
          <div class="col-lg-4 col-md-4 col-sm-4"></div>
        </div>
      </div>
      <div class="modal-footer">
        <div class="pull-left" style="display:block; width:50%; padding:15px;">
          <h4 class="pull-left">Credit available:</h4>
          <h4 class="pull-right"><%= credit_available %>$</h4>
        </div>
        <div class="pull-right" style="display:block; width:50%; padding:15px; border-left:#e5e5e5 solid 1px;">
          <h4 class="pull-left">Credit used:</h4>
          <h4 class="pull-right"><%= credit_used %>$</h4>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_catalogue_perk.html.erb
<div class="col-md-3 col-sm-4 col-xs-12">
  <div class="thumbnail">
    <%= image_tag perk.image.url(:thumb) %>
    <div class="caption">
      <h3><%= perk.name %></h3>
      <h5><%= perk.item_category.name %></h5>
      <p><%= perk.description %></p>
      <p>
        <a href="#" class="btn btn-default" role="button">info</a>
        <button type="button" class="btn btn-success pull-right" data-toggle="modal" data-target="#perk-<%= perk.id %>">Add perk</button>
      </p>
    </div>
  </div>
</div>

app/views/shared/_categories.html.erb
<ul class="nav nav-pills">
  <li role="presentation" class="active"><a href="#">All perks</a></li>
  <% @categories.each do |category| %>
    <li role="presentation"><a href="#cat5"><%= category %></a></li>
  <% end %>
</ul>

app/views/shared/_headline.html.erb
<div class="container">
  <h1>You still have <strong style="color:#828282;"><%= credit_available %>$</strong> of available credit.</h1>
  <p class="lead">You have to spend all your credit to enjoy perks.</p>
</div>

app/views/shared/_info_bar.html.erb
<div class="container" style="background-color: #F3F3F3; width: 100%; padding-top: 20px;">
  <div class="row">
    <div class="col-md-3 col-sm-6">
      <div class="panel panel-default">
        <div class="panel-body" data-toggle="tooltip" data-placement="bottom" title="Your used credit for this month">
          <h4 class="pull-left">Credit used:</h4>
          <h4 class="pull-right text-info"><%= credit_used %>$</h4>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-sm-6">
      <div class="panel panel-default">
        <div class="panel-body" data-toggle="tooltip" data-placement="bottom" title="You must spend all your budget each month. This is what remains actually.">
          <h4 class="pull-left">Credit available:</h4>
          <h4 class="pull-right text-success"><%= credit_available %>$</h4>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-sm-6">
      <div class="panel panel-default">
        <div class="panel-body" data-toggle="tooltip" data-placement="bottom" title="Time remaining to set your entire badget, otherwise your perks will not be active">
          <h4 class="pull-left">Days left:</h4>
          <h4 class="pull-right text-danger"><%= days_left %></h4>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-sm-6">
      <div class="panel panel-default">
        <div class="panel-body" data-toggle="tooltip" data-placement="bottom" title="This is your total monthly credit to spend">
          <h4 class="pull-left">Monthly credit:</h4>
          <h4 class="pull-right text-muted"><%= monthly_credit %>$</h4>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_my_perks_perk.html.erb
<div class="col-md-3 col-sm-4 col-xs-12">
  <div class="thumbnail">
    <a href="#"><span style="position: absolute; right: 22px; top: 8px;" class="fa fa-cog" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Manage account"></span></a>
    <%= image_tag perk.item.image.url(:thumb) %>
    <div class="btn-group btn-group-justified" role="group" aria-label="...">
      <div class="btn-group" role="group">
        <button type="button" class="btn btn-default" data-toggle="tooltip" data-placement="bottom" title="Go to your profile"><span class="fa fa-share-square-o" aria-hidden="true"></span></button>
      </div>

      <div class="btn-group" role="group">
        <%= form_tag item_subscription_path(perk.id), method: :patch, remote: true, id: perk.id do %>
            <%= hidden_field_tag 'item_subscription[id]', perk.id %>
            <%= select_tag 'item_subscription[amount]', options_for_select([["25$", 25], ["50$", 50], ["75$", 75], ["100$", 100], ["125$", 125], ["150$", 150], ["175$", 175], ["200$", 200]], selected: perk.amount.to_i), onchange: ("$('##{perk.id}').submit()"), class: 'form-control' %>
        <% end %>
      </div>

      <div class="btn-group" role="group">
        <%= link_to item_subscription_path(perk.id), method: :delete, remote: true, class: 'btn btn-default', data: {toggle: :tooltip, placement: :bottom}, title: "Cancel this perk"  do %>
          <span class="fa fa-times" aria-hidden="true"></span>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><%= image_tag 'logo_color.png', width: 100 %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= catalogue_path %>" class="<%= 'selected' if action_name == 'catalogue' %>">Catalogue</a></li>
        <li style="margin-right: 100px;"><a href="/subscriptions" class="<%= 'selected' if action_name == 'index' %>">My perks</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= avatar(current_user) %> <%= current_user.full_name %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Settings</a></li>
            <% if current_user.company_user.role_in_company == 'owner' %>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
            <% end %>
            <li class="divider"></li>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_order_items_create.html.erb
<div id="shopping-cart">
  <%= render 'shared/shopping_cart', total_checkout: @total_checkout %>
  <%= link_to 'Checkout', create_subscriptions_item_subscriptions_path, class: 'btn btn-success full-width-u' %>
</div>

app/views/shared/_pre_checkout_element.html.erb
<div class="row" style="padding: 20px;">
  <div class="col-md-2">
    <%= image_tag element.item.image, width: 80 %>
  </div>
  <div class="col-md-2" style="margin-top: 10px;">
    <p><%= element.item.description %></p>
    <p><%= element.amount.to_i %>$</p>
  </div>
</div>

app/views/shared/_request_demo.html.erb
<div class="row" style="background-color: #F1F1F1; margin: 40px 0">
    <div class="col-md-10 col-md-offset-1 col-sm-12 text-center wrap-ask" style="margin-top:40px;">
        <h3>Increase productivity, happiness and retention.</h3>
        <div class="form-container">
            <%= form_tag request_demo_invites_path, format: :json, method: :post, class: 'vanilla-form', id: form_id, novalidate: true do %>
                <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                <div class="column-50">
                    <input type="text" name="name" placeholder="Full name" required="required">
                    <input type="email" name="email" placeholder="Work e-mail address" required="required">
                </div><!--
                    Right column
                --><div class="column-50">
                    <input type="text" name="company" placeholder="Company name" required="required">
                    <input type="submit" value="Request a demo" data-error="Fix errors" data-processing="Sending..." data-success="Thank you!">
                </div>
                <footer class="notification-box"></footer>
            <% end%>
        </div>
    </div>
</div>

app/views/shared/_shopping_cart.html.erb
<h2 style="text-align: center;">Your Perks</h2>
<% if current_user.monthly_budget_left == 0 %>
  <div class="checkout">
    <div class="row">
      <div class="col-md-12">
        <p>
          You have no more credit for <%= display_full_next_month %>. You can always manage your perks by clicking above!
        </p>
      </div>
    </div>
  </div>
    <div class="row">
      <div class="col-md-12">
        <%= link_to 'Manage perks', item_subscriptions_path, class: "btn btn-success full-width-u" %>
      </div>
    </div>
  </div>
<% else %>
  <ul class="order-items">
    <% current_user.carts.order(:created_at).each do |cart_element| %>
      <%= render partial: 'shared/cart_element', locals: {cart_element: cart_element}%>
    <% end %>
  </ul>
  <br />
  <div class="checkout">
    <div class="row">
      <div class="col-md-12">
        <div class="col-md-7">
          <span class="total-checkout">
            Credit available:
          </span>
        </div>
        <div class="col-md-5">
          <span class="total-checkout-amount">
            $ <%= current_user.monthly_budget_left.to_i %>
          </span>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="col-md-7">
          <span class="total-checkout">
            Credit left:
          </span>
        </div>
        <div class="col-md-5">
          <span class="total-checkout-amount <%= 'has_error' if current_user.monthly_budget_left < @total_checkout %> ">
            $ <%= (current_user.monthly_budget_left - @total_checkout).to_i %>
          </span>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="col-md-7">
          <span class="total-checkout">
            Credit valid for:
          </span>
        </div>
        <div class="col-md-5">
          <span class="total-checkout-amount">
            <%= display_next_month %>
          </span>
        </div>
      </div>
    </div>
  </div>
  <br />
  <% if current_user.monthly_budget_left < @total_checkout %>
    <%= link_to 'Not enough credit :(', create_subscriptions_item_subscriptions_path, class: "btn btn-success full-width-u disabled" %>
  <% elsif @carts.empty? %>
    <%= link_to 'Empty cart', pre_checkout_item_subscriptions_path, class: "btn btn-success full-width-u disabled" %>
  <% elsif current_user.monthly_budget_left > @total_checkout %>
    <%= link_to "#{(current_user.monthly_budget_left - @total_checkout).to_i}$ still to add", pre_checkout_item_subscriptions_path, class: "btn btn-success full-width-u disabled" %>
  <% else %>
    <%= link_to 'Checkout', pre_checkout_item_subscriptions_path, class: "btn btn-success full-width-u" %>
  <% end %>
<% end %>

app/views/shared/_subscription_confirmation_element.html.erb
<div class="row" style="padding: 20px;">
  <div class="col-md-1">
    <div style="padding-top:5px;">
      <%= fa_icon("check", class: "fa-2x", style: "color: green; position: absolute; top: 5px; left: 5px;") if element.service_email.present? %>
      <%= image_tag element.item.image, width: 80 %>
      <p style="text-align:center; padding: 5px 0 0 0; width: 80px; font-size: 15px;" ><%= element.amount.to_i %>$</p>
    </div>
  </div>
  <div class="col-md-1">
  </div>
  <% if element.service_email.present? %>
    <div class="col-md-9" style="padding-top: 10px;">
      <p><h4>Nice!</h4></p>
      <p><h5>Your credit will be updated at the beginning of the next month.</h5></p>
    </div>
  <% else %>
    <div class="col-md-9">
      <div class="row">
        <div class="col-md-12"><p><h4>Oops, we haven't set up this account yet!</h4></p></div>
      </div>
      <div class="row">
        <div class="col-md-5">
          <p>What's your email you signed up for this service? </p>
          <%= form_for element, method: :patch, remote: true do |f| %>
            <%= f.text_field :service_email, type: :email, required: true %>
            <%= f.submit :submit %>
          <% end %>
        </div>
        <div class="col-md-1">or</div>
        <div class="col-md-5">
          <p>If you don't have an account for this service yet do it here: <%= link_to 'Signup with our custom URL', element.item.custom_signup_url, target: "_blank" %></p>
        </div>
      </div>
    </div>
  <% end %>
  <div class="col-md-1">
    <div style="padding-top: 40px;">
      <%= link_to "Remove", item_subscription_path(element.id), method: :delete, remote: true, class: 'btn btn-danger' %>
    </div>
  </div>
</div>