config/routes.rb
Rails.application.routes.draw do

  get '/yc_fellowship', to: 'pages#dashboard'
  get '/dashboard', to: 'pages#dashboard'
  get '/catalogue', to: 'pages#catalogue'

  resources :invites, only: [:new, :index, :create, :destroy] do
    collection do
      get 'activation/:invite_code', to: 'invites#activation', as: :activation
      get 'share', to: 'invites#share_invite_url_frontoffice'
      post 'create_account'
      post 'wizard_invite_done'
      post 'request_demo'
    end
  end
  resources :companies, only: [:update] do
    collection do
      get 'configure'
    end
  end
  resources :carts, only: [:create, :destroy, :update]
  resources :item_subscriptions, path: 'subscriptions', only: [:index, :edit, :update, :destroy, :create] do
    collection do
      get 'create_subscriptions'
      get 'pre_checkout'
    end
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pages/index'
  get 'pages/dashboard'
  get 'pages/catalogue'

  devise_for :users, path: 'account',
  path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' },
  controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  resources :items
  resources :item_categories

  resource :users do
    get 'new_credit_card', as: :new_credit_card
    post 'save_credit_card'
  end

  root 'pages#landing'

end

app/views/pages/catalogue.html.erb
<%= render partial: 'shared/info_bar' %>
<%= render partial: 'shared/headline' %>

<div class="container" style="padding-top:30px;">

  <%= render partial: 'shared/categories' %>

    <% @available_perks.each_slice(4) do |slice| %>
      <div class="row" style="padding-top:20px;" >
        <% slice.each do |perk| %>
          <%= render partial: 'shared/catalogue_perk', locals: {perk: perk} %>
        <% end %>
      </div>
    <% end %>
<!--     <div class="col-md-3 col-sm-4 col-xs-12">
      <div class="thumbnail">
      <img src="img/perk-logo.png" alt="...">
      <div class="caption">
        <h3>Suggest perk</h3>
        <p>What kind of service would you like to find on Workful?</p>
        <p><input type="text" class="form-control" placeholder="What about...?" aria-describedby="basic-addon1"></p>
        <p class=" text-center"><button type="button" class="btn btn-primary btn-group-justified">Suggest perk</button></p>
      </div>
    </div>-->
  </div>
</div>



<!--
********************MODAL ADD-PERK*******************
-->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <h3 class="modal-title" id="myModalLabel" style="text-align:center;">Add <strong>Company Name</strong> to your perks</h3>
        <p class="lead text-center">Set your monthly budget:</p>
        <div class="row">
          <div class="col-lg-4 col-md-4 col-sm-4"></div>
          <div class="col-lg-4 col-md-4 col-sm-4" style="margin-top:20px; margin-bottom:20px;">
            <div class="form-group pull-left">
              <select class="form-control" id="sel1">
                <option>25$</option>
                <option>50$</option>
                <option>75$</option>
                <option>100$</option>
                <option>125$</option>
                <option>150$</option>
                <option>175$</option>
                <option>200$</option>
              </select>
            </div>
            <button type="button" class="btn btn-success pull-right" data-dismiss="modal" aria-label="Close">Confirm</button>
          </div><!-- /.col-lg-6 -->
          <div class="col-lg-4 col-md-4 col-sm-4"></div>
        </div>
      </div>
      <div class="modal-footer">
        <div class="pull-left" style="display:block; width:50%; padding:15px;">
          <h4 class="pull-left">Credit available:</h4>
          <h4 class="pull-right"><%= credit_available %>$</h4>
        </div>
        <div class="pull-right" style="display:block; width:50%; padding:15px; border-left:#e5e5e5 solid 1px;">
          <h4 class="pull-left">Credit used:</h4>
          <h4 class="pull-right"><%= credit_used %>$</h4>
        </div>
      </div>
    </div>
  </div><!-- /.row -->
</div>



<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })</script>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="row" id="welcome-message">
    <div class="col-md-8">
      <% if @benefits_left_to_chose == 0 || current_user.monthly_budget_left < @total_checkout %>
        <h3>Welcome back <%= current_user.first_name %>, we're sorry but you cannot choose perks anymore :(</h3>
      <% else %>
        <h3>Welcome back <%= current_user.first_name %>, choose up to <%= pluralize @benefits_left_to_chose, 'perk' %> that you like!</h3>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <div class="categories" id="dashboard">
        <% @categories.each do |category| %>
          <div class="item-category">
            <h3><%= category.name %></h3>
            <div class="row">
              <% category.items.each do |item| %>
                <div class="item col-md-3 col-md-offset-1">
                  <div class="row" style="padding: 0 10px;">
                    <div class="item-image">
                      <span class="helper"></span><%= image_tag item.image.url(:thumb) %>
                    </div>
                  </div>
                  <div class="row">
                    <div class="item-name">
                      <%= item.name %>
                    </div>
                  </div>
                  <div class="row">
                    <%= form_tag carts_path, remote: true do %>
                      <div class="item-info">
                        <div class="col-md-12">
                          <%= hidden_field_tag :item_id, item.id %>
                          <%= hidden_field_tag :amount, 25 %>
                          <%= item.description %>
                        </div>
                      </div>
                      <div class="item-actions">
                        <% if @item_in_cart.include?(item.id) %>
                          <button class="btn btn-success full-width-u disabled">Added</button>
                        <% elsif current_user.monthly_budget_left <= @total_checkout %>
                          <button class="btn btn-success full-width-u disabled">No more credit</button>
                        <% elsif @items_already_subscribed.include?(item.id) %>
                          <button class="btn btn-success full-width-u">Add credit</button>
                        <% else %>
                          <button class="btn btn-success full-width-u">Add</button>
                        <% end %>
                      </div>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-md-3 col-md-offset-1 box-white shopping-cart-box">
      <div id="shopping-cart">
        <%= render 'shared/shopping_cart' %>
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>